name: Main Pipeline

on: push

jobs:
  checkversion:
    name: Check Version
    runs-on: ubuntu-latest
    env:
      REPOSITORY_MAIN_BRANCH: $REPOSITORY_MAIN_BRANCH
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # install the python version needed

      - name : running check version

        run: |
          echo "checking version"
          echo "Main Branch name: $REPOSITORY_MAIN_BRANCH"
          python checkversion.py

  