name: Main Pipeline

on: push

jobs:
  checkversion:
    name: Check Version
    runs-on: ubuntu-latest
    env:
      REPOSITORY_MAIN_BRANCH: $REPOSITORY_MAIN_BRANCH
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name : running check version
        run: |
          echo "checking version"

      - name: Install dependencies
        run: |
          echo "Installing Dependencies..."
          echo "Use the latest pip"
          python -m pip install --upgrade pip
          echo "Installing GitPython"
          pip install GitPython
      - uses: actions/checkout@v3
      - run:  |
              echo
              *************************************** \
              *                                     * \
              *            Check Verion             * \
              *                                     * \
              ***************************************
      - run: python "utilities/checkversion.py"


  
  
