name: Main Pipeline

on: push

jobs:
  checkversion:
    name: Check Version
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # install the python version needed

      - name : running check version
        env:
          MAIN_REPOSITORY_BRANCH: ${{ Variables.MAIN_REPOSITORY_BRANCH }}
        run: echo checking version \n
             python checkversion.py

  