name: Main Pipeline

on: push

env:
  MAIN_REPOSITORY_BRANCH: ${{ REPOSITORY_MAIN_BRANCH }}

jobs:
  checkversion:
    name: Check Version
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # install the python version needed

      - name : running check version
        run: echo checking version \n
             python checkversion.py

  